include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "/*.g.dart"
    - "/*.freezed.dart"
    - "/*.gr.dart"
    - "/*.mocks.dart"

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    use_key_in_widget_constructors: true
    no_logic_in_create_state: true
    sort_constructors_first: true
    unnecessary_this: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_returning_null: true
    avoid_setters_without_getters: true
    prefer_final_fields: true
    prefer_final_locals: true
    constant_identifier_names: false  # Allow flexibility in constants naming